[build]
  publish = "."

[functions]
  directory = "."
  node_bundler = "esbuild"

[functions.generate]
  timeout = 26

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
